--declaring the err function
function err()

    --printing an error phrase
    print("error, try again")

end
